name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
      # - uses: julia-actions/julia-uploadcoveralls@v1
      #  env:
      #    COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 300
    permissions:
      contents: write
    steps:
      - name: Add GLMakie/XFVB dependencies
        run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Julia cache
        uses: julia-actions/cache@v2
      - name: "BuildPkg"
        uses: julia-actions/julia-buildpkg@v1
      - name: "docdeploy"
        uses: julia-actions/julia-docdeploy@v1
        with:
          prefix: xvfb-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY: :0
      - name: Doc build
        run: |
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using JutulDarcy
            DocMeta.setdocmeta!(JutulDarcy, :DocTestSetup, :(using JutulDarcy); recursive=true)
            doctest(JutulDarcy)'
